---
- name: ufw | install
  apt: pkg=ufw
       update-cache=yes
       state=latest

- name: ufw | deny incoming
  shell: ufw default deny incoming

- name: ufw | allow outgoing
  shell: ufw default allow outgoing

- name: ufw | allow in ssh
  shell: ufw allow in ssh

- name: ufw | allow in http
  shell: ufw allow in http

- name: ufw | enable
  shell: echo 'y' | ufw enable

- name: ufw | start on boot
  service: name=ufw
           enabled=yes
